replicas: 1
image: lscsde/analytics-workspace-mgmt:0.1.6
nodeSelector: {}
tolerations: []
volumes: []
volumeMounts: []
env: []
resources: {}

ingress:
  enabled: false
  className: nginx
  host: "workspace-mgmt.xlscsde.local"
  annotations: {}
  tls:
    enabled: false
    secretName: ""

service:
  port: "8000"