apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analyticsdatasourcebindings.xlscsde.nhs.uk
spec:
  scope: Namespaced
  group: xlscsde.nhs.uk
  names:
    kind: AnalyticsDataSourceBinding
    plural: analyticsdatasourcebindings
    singular: analyticsdatasourcebinding
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                comments:
                  type: string
                  description: Any comments relating to this binding.
                workspace:
                  type: string
                  description: REQUIRED. The name of the workspace in kubernetes
                expires:
                  type: string
                  format: date
                  description: The date at which this binding expires 
                datasource:
                  type: string
                  description: The datasource to match
                approvals:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The type of approval being given
                      name:
                        type: string
                        description: The name of the approver
                      email:
                        type: string
                        description: The email address of the approver
                      jobTitle:
                        type: string
                        description: The job title of the approver
                      approvalGiven:
                        type: string
                        format: date-time
                        description: The time at which approval was given by the user
                    required:
                    - type
                    - name
                    - email
                    - jobTitle
                    - approvalGiven
              required:
                - workspace
                - datasource
            status:
              type: object
              properties:
                statusText:
                  type: string
                lastActiveCheck:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Workspace
        type: string
        jsonPath: .spec.workspace

      - name: DataSource
        type: string
        jsonPath: .spec.datasource

      - name: Status
        type: string
        jsonPath: .status.statusText
