apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analyticsdatasources.xlscsde.nhs.uk
spec:
  scope: Namespaced
  group: xlscsde.nhs.uk
  names:
    kind: AnalyticsDataSource
    plural: analyticsdatasources
    singular: analyticsdatasource
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                type:
                  type: string
                  description: The type of data source
                displayName:
                  type: string
                  description: Display name of the data source
                description:
                  type: string
                  description: A description of the data source
                license:
                  type: string
                  description: A description of the license for this data dource

                publisher:
                  type: object
                  properties:
                    organisation:
                      type: string
                      description: Name of the organisation
                    contact:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the contact
                        role:
                          type: string
                          description: The role of this contact
                
                project:
                  type: object
                  properties:
                    id:
                      type: string
                      description: The Unique ID of the project in question

                connections:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The type of description being configured
                      name:
                        type: string
                        description: The name of the connection
                      
                      connectionString:
                        type: object
                        properties:
                          secretName:
                            type: string
                            description: If the connection string contains secrets, populate a secret and reference it here
                          value:
                            type: string
                            description: If the connection string doesn't contain secrets, populate it here.
                        anyOf:
                          - properties:
                            required:
                            - secretName
                          - properties:
                            required:
                            - value
                      databricksConnection:
                        type: object
                        properties:
                          hostName:
                            type: string
                            description: The hostname of the databricks instance
                          httpPath:
                            type: string
                            description: The path of the databricks instance
                          personalAccessToken:
                            type: object
                            properties:
                              secretName: 
                                type: string
                                description: Name of the secret that contains the personal access token related to this datasource
                              secretKey:
                                type: string
                                description: The key in the secret that contains token
                                default: TOKEN
                          oauth2Token:
                            type: object
                            properties:
                              secretName: 
                                type: string
                                description: Name of the secret that contains the oauth2 token related to this datasource
                              secretKey:
                                type: string
                                description: The key in the secret that contains token
                                default: TOKEN
                          servicePrinciple:
                            type: object
                            properties:
                              secretName: 
                                type: string
                                description: Name of the secret that contains the oauth2 token related to this datasource
                              

                        anyOf:
                          - properties:
                            required:
                            - personalAccessToken
                          - properties:
                            required:
                            - oauth2Token
                    anyOf:
                      - properties:
                        required:
                        - connectionString
                      - properties:
                        required:
                        - databricksConnection                                
                approvals:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The type of approval being given
                      name:
                        type: string
                        description: The name of the approver
                      email:
                        type: string
                        description: The email address of the approver
                      jobTitle:
                        type: string
                        description: The job title of the approver
                      approvalGiven:
                        type: string
                        format: date-time
                        description: The time at which approval was given by the user
                    required:
                    - type
                    - name
                    - email
                    - jobTitle
                    - approvalGiven
            status:
              type: object
              properties:
                statusText:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Title
        type: string
        jsonPath: .spec.title

      - name: Status
        type: string
        jsonPath: .status.statusText