apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analyticsdatasourcebindings.xlscsde.nhs.uk
spec:
  scope: Namespaced
  group: xlscsde.nhs.uk
  names:
    kind: AnalyticsDataSourceBinding
    plural: analyticsdatasourcebindings
    singular: analyticsdatasourcebinding
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                comments:
                  type: string
                  description: Any comments relating to this binding.
                workspace:
                  type: string
                  description: REQUIRED. The name of the workspace in kubernetes
                expires:
                  type: string
                  format: date
                  description: REQUIRED. The date at which this binding expires 
                datasource:
                  type: string
                  description: The datasource to match

              required:
                - workspace
                - datasource
                - expires
            status:
              type: object
              properties:
                statusText:
                  type: string
                lastActiveCheck:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Workspace
        type: string
        jsonPath: .spec.workspace

      - name: DataSource
        type: string
        jsonPath: .spec.datasource

      - name: Expires
        type: string
        jsonPath: .spec.expires

      - name: Status
        type: string
        jsonPath: .status.statusText
