apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: analyticscrates.xlscsde.nhs.uk
spec:
  scope: Namespaced
  group: xlscsde.nhs.uk
  names:
    kind: AnalyticsCrate
    plural: analyticscrates
    singular: analyticscrate
    shortNames:
    - ac
    categories:
    - krap
    - krap-core
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: 
                displayName:
                  type: string
                  description: REQUIRED. The short display name used as the title for the workspace.
                description:
                  type: string
                  description: REQUIRED. A simple description which can be multiple lines describing the workspace
                path:
                  type: string
                  description: The path to the file in the repository which contains the ro-crates metadata.
                  default: /ro-crate-metadata.json
                repo:
                  type: object
                  properties:
                    url:
                      type: string
                      description: The URL of the git repository
                    branch:
                      type: string
                      description: The branch on the git repository to use
                      default: main
                    secretName:
                      type: string
                      description: The name of the secret containing any information required to connect to the git repo
                    secretKey:
                      type: string
                      description: The key inside of the secret to use
                      default: TOKEN
            status:
              type: object
              properties:
                statusText:
                  type: string
                  default: "Waiting"
                  nullable: false
                commitId:
                  type: string
                workspace:
                  type: string                      
      subresources:
        status: {}
      additionalPrinterColumns:
      - name: Workspace
        type: string
        jsonPath: .status.workspace

      - name: Status
        type: string
        jsonPath: .status.statusText