apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.service.port }} 
    targetPort: 8000