name: Generate CRD's

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'


jobs:
  build-java-crd:
    uses: lsc-sde/lsc-sde/.github/workflows/generate-java-crds.yaml@main
    with:
      repository: lsc-sde/java-analytics-workspace-management-models
      crds: 'templates/AnalyticsWorkspace.yaml,templates/AnalyticsWorkspaceBinding.yaml'
      generatingJavaPackage: io.github.lsc-sde.analytics.workspace.management
      crdApiGroupPrefix: uk.nhs.xlscsde
    secrets: inherit